%% Generated by the Erlang ASN.1 compiler version:1.6.13
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module RSA



-record('WrappedKey',{
seq, publicKey}).

-record('WrappedKey_seq',{
rsaIdentifier, null}).

-record('RSAPublicKey',{
modulus, publicExponent}).

